server:
  extraFlags:
    - web.enable-remote-write-receiver

  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
      cluster: ptic
      source: prometheus

  persistentVolume:
    enabled: false

  retention: 6h

  resources:
    requests: { cpu: 50m, memory: 256Mi }
    limits: { cpu: 500m, memory: 1Gi }

scrapeConfigs:
  kubernetes-api-servers:
    enabled: false
  kubernetes-nodes:
    enabled: false
  kubernetes-nodes-cadvisor:
    enabled: false
  kubernetes-pods:
    enabled: false
  kubernetes-pods-slow:
    enabled: false
  kubernetes-service-endpoints:
    enabled: false
  kubernetes-service-endpoints-slow:
    enabled: false
  kubernetes-services:
    enabled: false
  prometheus-pushgateway:
    enabled: false

serverFiles:
  prometheus.yml:
    rule_files: []

alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
