apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:0gXbnQsCt0LlfV2dakglvr2flJk=,iv:QA4ccNue5g5B24ahplnmNBr3qw0/G31Jm6BrdBger+0=,tag:VfBl01aKWi3Zc+8gG0+dEg==,type:str]
    secretKey: ENC[AES256_GCM,data:qBevx7PysYpuXnnUyXCApn3X21wG6ueqxmuHzCN0uFLnQFu1MYcnSYbv/e8=,iv:yllqYGb87d+7vjGZWsKKdUXycjTyeKgVRVDnZrSIL70=,tag:3FckvXHjzRaidfwK2ZPzeA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgres-backup
    namespace: postgres
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNkVqRDhydEhlUkJaVzB5
            ckw0Vzh3dWpUM0R2cTV4WndtU3RFMjZnbDFFClo3bjhPSTlRNjQ2SFFiZTN6blFk
            bXdNZW81WUN4eFlYd1F6c2tmUS94cDgKLS0tIHFkL3dRYS92THl1dTl0amdDM01F
            aWlncmVrWVlUV2kvRU9MYlVrREpTUjQKYMbvS+YSmUQsG/Djf1nQzGsqlQhvh9kO
            acrxQwDfIooVivsjjB3lwwpmVh67SJabOpQP+n5exEb08YsTaXBT+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163t9ntrs899qmqfnl7cdlwgvwwlysak9rajgcj4waz9ft9fug4fqgufp5h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T09:05:34Z"
    mac: ENC[AES256_GCM,data:J4v5Gv/3ZpipJVLZJorBGN3r0VNl4n72LqlmQC1KWyMSZs/Y4fxb/lNjFLndI/0KzQFogy8YBVtGoBwWo/2TJD5IiPH+Ad916/n8sFu8f1qdV+EzEyBbeQwfm399vLZw0hmE0NSCmjkk3fBwpQX5uh8WmPEH5PfI3RbAMdaRTWY=,iv:xH4v4maWXODHSc0fieM4cmLOgMFB7+O1mfG45bGljjU=,tag:+5LA86yCxmv/L9DlT2etSA==,type:str]
    version: 3.13.3
