apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TZlN24qCpPiDmMFa0MSzG730BXUZCejhEKSNOpXwaF8=,iv:einLz1aoDWCcGpi25Kg4egAPSGLOoGimmOrhNh0n8UY=,tag:7zmDlrCX/vQ0PnrWiNhd6Q==,type:str]
    username: ENC[AES256_GCM,data:P3MrmQ==,iv:jF0Da542xanqQOnpyfFM4LdMebLaRIPpxnmBqjBEIII=,tag:9xxNS4wNow/rrv2mGBW6oA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-db
    namespace: postgres
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYVZ5c0orZU9zRFBUOTBk
            THZ4SnNSdTBvK1ZYZWhTNnF1QS9HMWhtT0FNCkhKb2RUUkJVZkZHUkVGTmZWRFd1
            VHpTdUNJcW1HaGs2T2RFN3NvY1Z5YlEKLS0tIDJrL05jRW4rUXpxNVN4UWIzMW9X
            aFlnYlc5Y21zNVNzVFcwcGsyRTd1VlkKLRdmXQHY7H3MbMWLjeQp1JxTJvlnZWoL
            0/M70kQ82s042/F4oct1p+l9jyIrlANnoKYxtaT9gtLrEco29Xhdfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163t9ntrs899qmqfnl7cdlwgvwwlysak9rajgcj4waz9ft9fug4fqgufp5h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:04:03Z"
    mac: ENC[AES256_GCM,data:UzQI5Emwhetw4cScEKz49RXsp7FftEmbwCMmkTQ/J6Pm6KmJcELGsC9Pkd6L+/Fo/EYvx1oWsqAeSyVvSX8tsFlxpKjg1uzaOd9sb3hu+56njgNEN1dPY3vF58nrLm23j0SlmuPDy93NajXJSBxWZpIOVwRxXj0Ln6Uecu2/tYQ=,iv:WEc/C9gT6sHDBHyuCdCgoYrdoMQod98kKbW+6XDKKIg=,tag:Jshp4unvPv8mqRRSFeptJQ==,type:str]
    version: 3.13.3
