apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./backup-credentials.sops.yaml
  - ./role-credentials.sops.yaml
