apiVersion: v1
data:
    password: ENC[AES256_GCM,data:W8QWUK7d6ISdhbyd6b0+VusDY0rs4eMNUg2gEca3iJQ=,iv:QlUMHYM9fsS9X6F3KL50C+iPQZNN0/SudTkMEAnt1t4=,tag:i0uUoVNJ0RPvjZW4E5vxgw==,type:str]
    username: ENC[AES256_GCM,data:ebYh9A==,iv:qx9sldIhUoRqCVvbD5/GcIisgZg6hpCf2XHOkbI8ouw=,tag:2XwVJ2M0LHbCZqfz/5YDUw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-db
    namespace: apps
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMlRUWkRFa2MvNXVSd3k0
            Z3lKeGk5Z0dSR3BzZ1pTc25TU2E4L2lrSFMwCmVzN3Vvd3JxU05JU2ZHZjk5VG5i
            ZFFmUjFJdFAyRlUzaS9XVjUxY2svTm8KLS0tIGQ1K2tGcDYrRVlyTmpmQVZldTd4
            d2VCWFgyL1hqdHhWRFphYXRiQzBtRFkKIuW71Fg966Sbhz/+rfg1t4w3PXN80OJZ
            wKdd9G9Bb05plFlp1+VszMPUWRUOu1JB3t1cXP5yCHR+eGsNixwGlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163t9ntrs899qmqfnl7cdlwgvwwlysak9rajgcj4waz9ft9fug4fqgufp5h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:04:03Z"
    mac: ENC[AES256_GCM,data:33kfEl0OE+w6M16ey+qaE7prlVeFtemkHRT3ewz1+fpjhmJ2/VcKSmI6yphK+ZdUddAZ/92ZGg3RjyUiBkDBFEvRk7H2d5ylA34J1BKWjZQ5W9o44QayVFZg3AgVJYshWP8xTuVcBbd9+yp8Vay9tu9VfuERzcGHDiHAqlqrQRs=,iv:bPfT7zpk8f6zHTgRCQOhuvcEU2jmn7Gl61h5Uk1m4OI=,tag:Vu8lU4zucN4WqMPrUc9akA==,type:str]
    version: 3.13.3
