apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: backend-db-credentials
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./db-credentials.sops.yaml
