apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:DTSPszo0tLlB90oFTRKF9wOXONk=,iv:iYwd6P/dXjlBJECU/70pZl2QR7h+bE7SZn3+i91rqPo=,tag:4o0zo2VfxrXbgWjiisKUKA==,type:str]
    secretKey: ENC[AES256_GCM,data:bMIv/DJ3/9VhvNZw3NFpwspKWH9EhxN15iin+SoUFgaQQNPomv5uzZibaqE=,iv:sqod5Ep8B7qBv4oEh6ZBsStt1quD/zl6eQ4m4by4lIY=,tag:duh6RNZ8hc8hH2SrpDHiZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rustfs
    namespace: rustfs
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS1hzOWxGNXFmeHRaU21n
            TXhvU2tOdmxYckNkRzdzL3BuSnJ2YU9rbWtFClZHVEtkRC9VeVpTaXJNLzdSejBu
            aU9tcHhNcnVkUWliMnVHSTZKdllTTlUKLS0tIDVFVUlNcVhZemJHc05KZWYzZUF2
            ZVlHcDNZY2tKbUhNcG9sR3NWbWNjdlkKDXn784owtr2NhMf9jJazfU7qYTcvpWUs
            p5cAKDQ+FMQzjWgYWGdqEwCiojLGz91GSDhQe5rY2YHPvod4XWllEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163t9ntrs899qmqfnl7cdlwgvwwlysak9rajgcj4waz9ft9fug4fqgufp5h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T07:53:33Z"
    mac: ENC[AES256_GCM,data:KnT50aniTR+mqvY9B58KPx/vYxefqcpVKc2gI4+dJwu+8m1Zi93r9CSrF1PjMhmq3wqlLWYTATLRARfAUthHDo8McxI8YIbwNmyMy8p6TwRXVtdIaJt8x273red1kOpHtV8sRCRqcHWytvnG8ELKJUIlzHFpDL1bsbePXR9iYbo=,iv:udcpDxyFhs4dtjHCVU1mXI7pUbAiunw15EGiY/mkEDs=,tag:ldPB2de6GHtDPB2Nm7q0iQ==,type:str]
    version: 3.13.3
