replicas: 1

persistence:
  enabled: false

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits: { cpu: 500m, memory: 512Mi }

adminPassword: ""

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin
  auth:
    disable_login_form: true
  analytics:
    reporting_enabled: false
    check_for_updates: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local:80
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo

      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '"traceid":"(\w+)"'
              datasourceUid: tempo
              url: "$${__value.raw}"
            - name: TraceID
              matcherRegex: 'traceid=(\w+)'
              datasourceUid: tempo
              url: "$${__value.raw}"

      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            filterByTraceID: true
            filterBySpanID: false
            customQuery: true
            query: '{deployment_environment="$${__span.tags.deployment_environment}"} | json | traceid = `$${__span.traceId}`'
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            tags:
              - key: service.name
                value: service_name
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: loki

