apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:3pws/2f4KPisPyhred4EeumOAt7VZ8XzK2oT1VgxPUXVP0IkRg0eh9HrkrYP+N24adwMlzmmRVA82EueP3SZj7iXw0m7h3EevJgj+N3BGSpc8KvQuxltcJtB6fMJRMAUWHuMSrZeTXawvor55yvQaEehdi1RPHbEt8oOUS8uauCp8JRLV9y5D7ygJEE3TY+xAvGjxaGzEWFeqYiGnobIzcdLqoSa11zv5q2ITgauprRdmdHsWmri1EvXXQFafzEBPij9ROz6gGvrmzRUoecZr5NP/kbS0qpxMcyJirMlrNeivbcjkkqNDCb+N/w=,iv:Xqf8IHseh2iY3TskNCsAX08KWMwHQtQMilBHi2O+3bY=,tag:H2HV8RlvYF8k0JthLR247g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflared-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTGNvako2RDhQN0dzeXRr
            NERyU2VWZFlhRVFxTWFPanR0bnhNVzlwYWlJCnhmNnJ5bkVhb2h0dExCbVZRc0My
            SjhtaW9yMkdjKzhKeDkyRW5pTXM5M0EKLS0tIE1lS2ZJVkFubm53aThSZ2FwRHBP
            QlhtQ3VhaHpCWjU5RkE4QjhvRWZWQ1kKdgYhpy3oWPQj6MVrPSzk1IvCVGyi0o9/
            sXT7x0rACFDXeltqF8Z8iubXKRent7BQsfBgiVzpfoYERcl+Tl0+hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163t9ntrs899qmqfnl7cdlwgvwwlysak9rajgcj4waz9ft9fug4fqgufp5h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T03:32:02Z"
    mac: ENC[AES256_GCM,data:dhTHTW7nbMQDJ28yijxFhtDV56w9mC8QcBzEWjiwmtuMxS0Aa6XZNsPmKahnQ02iUWwARlT048oyo21v8Yhv+pe80NToOmyP3JxxZ/IG13o4DVy6YWLyUIPoYHsDYKMxrY7BMEPAfJ4iuhYfIalVmji0F68T/uHzpXxaQbs8pxk=,iv:fFL9M3dl5j7k4Nf0wMnJxHluerj3a2qMJiDZLswxRNc=,tag:dLf/N8uPA2vm/rFUhDRB8A==,type:str]
    version: 3.13.3
